config/routes.rb
ShadowPlayInRails::Application.routes.draw do

  

  get "shadow_play/home"

  get "shadow_play/example"

  get "shadow_play/page"

  get "shadow_play/ano_page"

  get "shadow_play/contact"

   match '/' => 'shadow_play#home'

  match '/home' => 'shadow_play#home'

  match '/example' => 'shadow_play#example'

  match '/page' => 'shadow_play#page'

  match '/ano_page' => 'shadow_play#ano_page'

  match 'contact' => 'shadow_play#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shadow_play_controller.rb
class ShadowPlayController < ApplicationController
  def home
  end

  def example
  end

  def page
  end

  def ano_page
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shadow_play_helper.rb
module ShadowPlayHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <p><%= link_to 'Home', home_path %>| <%= link_to 'Example', example_path %> |<%= link_to 'Page', page_path %> | <%= link_to 'Another Page', ano_page_path %> | <%= link_to 'Contact', contact_path %></p>
  <p>Copyright &copy; shadowplay_2 | <%= link_to 'HTML5', "http://validator.w3.org/check?uri=referer" %> | <%= link_to 'CSS', "http://jigsaw.w3.org/css-validator/check/referer" %> | <%= link_to 'design from HTML5webtemplates.co.uk', "http://www.html5webtemplates.co.uk" %></p>
</div>

app/views/layouts/_header.html.erb
 <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><%= link_to 'shadow play', home_path%> </h1>
          <h2>Simple. Contemporary. Website Template.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li class="selected"><%= link_to 'Home', home_path %></a></li>
          <li><%= link_to 'Example', example_path %> </li>
          <li><%= link_to 'Page', page_path %> </li>
          <li><%= link_to 'Another Page', ano_page_path %> </li>
          <li><%= link_to 'Contact', contact_path %></li>
        </ul>
      </div>
    </div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
        <!-- insert your sidebar items here -->
        <h3>Latest News</h3>
        <h5>January 1st, 2011</h5>
        <p>2011 sees the redesign of our website. Take a look around and let us know what you think.<br /><%= link_to 'Read more', '#' %></p>
        <h5>January 1st, 2011</h5>
        <p>2011 sees the redesign of our website. Take a look around and let us know what you think.<br /><%= link_to 'Read more', '#' %></p>
        <h3>Useful Links</h3>
        <ul>
          <li><%= link_to 'link 1', '#'%> </li>
          <li><%= link_to 'link 2','#'%></li>
          <li><%= link_to 'link 3','#'%></li>
          <li><%= link_to 'link 4','#'%></li>
        </ul>
        <h3>Search</h3>
        <form method="post" action="#" id="search_form">
          <p>
            <input class="search" type="text" name="search_field" value="Enter keywords....." />
            <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="/assets/search.png" alt="Search" title="Search" />
          </p>
        </form>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShadowPlayInRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main">
   <%= render 'layouts/header' %>
    <div id="content_header"></div>
    <div id="site_content">
      <%= render 'layouts/sidebar' %>
      <%= yield %>
    </div>
    <div id="content_footer"></div>
   <%= render 'layouts/footer' %>
  </div>


</body>
</html>

app/views/shadow_play/ano_page.html.erb
<div id="content" style="text-align: justify">
  <!-- insert the page content here -->
  <h1>Another Page</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
</div>

app/views/shadow_play/contact.html.erb
<div id="content">
  <!-- insert the page content here -->
  <h1>Contact Us</h1>
  <p>Below is an example of how a contact form might look with this template:</p>
  <form action="#" method="post">
    <div class="form_settings">
      <p><span>Name</span><input class="contact" type="text" name="your_name" value="" /></p>
      <p><span>Email Address</span><input class="contact" type="text" name="your_email" value="" /></p>
      <p><span>Message</span><textarea class="contact textarea" rows="8" cols="50" name="your_enquiry"></textarea></p>
      <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="contact_submitted" value="submit" /></p>
    </div>
  </form>
  <p><br /><br />NOTE: A contact form such as this would require some way of emailing the input to an email address.</p>
</div>

app/views/shadow_play/example.html.erb
<div id="content">
  <!-- insert the page content here -->
  <h1>Examples</h1>
  <p>This page contains examples of all the styled elements available as part of this design. Use this page for reference, whilst you build your website.</p>
  <h2>Headings</h2>
  <p>These are the different heading formats:</p>
  <h1>Heading 1</h1>
  <h2>Heading 2</h2>
  <h3>Heading 3</h3>
  <h4>Heading 4</h4>
  <h5>Heading 5</h5>
  <h6>Heading 6</h6>
  <h2>Text</h2>
  <p>The following examples show how the text (within '&lt;p&gt;&lt;/p&gt;' tags) will appear:</p>
  <p><strong>This is an example of bold text</strong></p>
  <p><i>This is an example of italic text</i></p>
  <p><a href="#">This is a hyperlink</a></p>
 
</div>

app/views/shadow_play/home.html.erb
<div id="content">
        <!-- insert the page content here -->
        <h1>Welcome to the shadowplay_2 template</h1>
        <p>This standards compliant, simple, fixed width website template is released as an 'open source' design (under a <a href="http://creativecommons.org/licenses/by/3.0">Creative Commons Attribution 3.0 Licence</a>), which means that you are free to download and use it for anything you want (including modifying and amending it). All I ask is that you leave the 'design from HTML5webtemplates.co.uk' link in the footer of the template, but other than that...</p>
        <p>This template is written entirely in <strong>HTML5</strong> and <strong>CSS</strong>, and can be validated using the links in the footer.</p>
        <p>You can view more free HTML5 web templates <a href="http://www.html5webtemplates.co.uk">here</a>.</p>
        <p>This template is a fully functional 5 page website, with an <a href="examples.html">examples</a> page that gives examples of all the styles available with this design.</p>
        <h2>Browser Compatibility</h2>
        <p>This template has been tested in the following browsers:</p>
        <ul>
          <li>Internet Explorer 8</li>
          <li>FireFox 3.5</li>
          <li>Google Chrome 13</li>
        </ul>
      </div>

app/views/shadow_play/page.html.erb
<div id="content" style="text-align: justify">
  <!-- insert the page content here -->
  <h1>A Page</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
</div>